Global:
  debug: false
  use_gpu: true
  epoch_num: 1500
  log_smooth_window: 20
  print_batch_step: 25
  save_model_dir: ./models/
  save_epoch_step: 25
  eval_batch_step: 500
  cal_metric_during_train: true
  pretrained_model: ./models/en_PP-OCRv3_rec_train/best_accuracy.pdparams
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  infer_img: ./data/test/test.png
  character_dict_path: ./PaddleOCR/ppocr/utils/license_plates.txt
  max_text_length: &max_text_length 15
  infer_mode: false
  use_space_char: false
  distributed: true
  save_res_path: ./models/lp.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Piecewise
    decay_epochs : [700]
    values : [0.00004, 0.000008]  
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    factor: 0


Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
  Neck:
    name: SequenceEncoder
    encoder_type: svtr
    dims: 64
    depth: 2
    hidden_dims: 120
    use_guide: False
  Head:
    name: CTCHead
    fc_decay: 0.00001
Loss:
  name: CTCLoss

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/train
    ext_op_transform_idx: 1
    label_file_list:
    - ./data/train_brazil.txt
    - ./data/train_common.txt
    ratio_list: [0.2, 1]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    # - RecConAug:
    #     prob: 0.5
    #     ext_data_num: 2
    #     image_shape: [48, 320, 3]
    #     max_text_length: *max_text_length
    - RecAug:
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: true
    batch_size_per_card: 128
    drop_last: false
    num_workers: 8

    
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./data/val
    label_file_list:
    - ./data/val_brazil.txt
    - ./data/val_common.txt
    ratio_list: [0.2, 1]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - CTCLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label
        - length
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 128
    num_workers: 8
